---
- name: Patch broken postgresql logrotation
  copy:
    dest: /etc/logrotate.d/postgresql-cleanup
    content: |
      /var/log/postgresql/postgresql-2???-??-??_* {
        daily
        rotate 0
        maxage 15
        su root root
      }

- name: Create Users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    encrypted: "{{ item.encrypted }}"
  when: "inventory_hostname == 'master'"
  with_items:
    - "{{ postgresql_users }}"

- name: Create Databases
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
  when: "inventory_hostname == 'master'"
  with_items:
    - "{{ postgresql_databases }}"

- name: Assign privileges
  postgresql_privs:
    role: "{{ item.name }}"
    db: "{{ item.db }}"
    privs: "{{ item.priv }}"
    objs: "ALL_IN_SCHEMA"
  when: "inventory_hostname == 'master'"
  with_items:
    - "{{ postgresql_user_privileges }}"
